### ISSUE TITLE
[Feature] To-do-list

### ISSUE THREAD

**Issue by ahmadxgani** [QUERY-GANI/simple-blog-backend#1]
## Improvement/Refactor And Optimize Code
- [x] Custom Scalar For Upload Image
- [ ] on production: validation json string to be a valid json format in content field
- [ ] add dkim to secure message on email
- [ ] refactor folder structure, transfer input object type to dto folder and entity file to entities folder, if the file is more than one
- [ ] [args vs input type?](https://github.com/MichalLytek/type-graphql/issues/646) :thinking: 
- [ ] optimize performance in resolve field that apply a middleware, why the guard/interceptor is called each resolve field? expected that called once but idk how to do that
- [x] limit nested sub-field depth
- [x] custom authorization scope
## Bug and Error
- [x] Cannot be running on prod cuz a problem with faker library
- [x] Issue with auth, a user only  can update their own data
- [x] seeder not working after switching to lib [@jorgebodega/typeorm-seeding](https://github.com/jorgebodega/typeorm-seeding/issues/193)
- [ ] fix cascade on delete tag
- [x] cookies doesn't set after login mutation? previously works as well?
## To-do Feature
- [x] Delete all tables from typeorm cli
- [x] Manage image with [imgbb](https://api.imgbb.com/)
- [ ]  Log out every where using sessions method (change authentication method and make a session entity)
- [x] [error on delete post](https://github.com/typeorm/typeorm/issues/8310)
- [ ] rate limiting | api request
